//! Byte-exactness of the SentencePiece unigram tokenizer against
//! `sentencepiece` itself, using the GLiNER2.5-Decide vocabulary.
//!
//! The fixture is generated by `/tmp` script `dump_spm.py` (kept out of the
//! repo because it needs the `sentencepiece` wheel):
//!
//! ```text
//! spm.encode(text, out_type=str)  ->  pieces
//! spm.encode(text, out_type=int)  ->  ids
//! ```

use rust_model_inference::core::sentencepiece::SentencePieceTokenizer;

const MODEL: &str = "models/GLiNER2.5-Decide/spm.model";
const FIXTURE: &str = "tests/fixtures/gliner2-decide/spm-pieces.json";

fn tokenizer() -> SentencePieceTokenizer {
    let path = std::path::Path::new(MODEL);
    assert!(
        path.exists(),
        "missing {MODEL}; download fastino/GLiNER2.5-Decide first"
    );
    let bytes = std::fs::read(path).expect("read spm.model");
    SentencePieceTokenizer::from_model_proto(&bytes).expect("parse spm.model")
}

fn fixture() -> serde_json::Value {
    let text = std::fs::read_to_string(FIXTURE)
        .unwrap_or_else(|_| panic!("missing {FIXTURE}; regenerate with dump_spm.py"));
    serde_json::from_str(&text).expect("parse fixture")
}

#[test]
fn matches_sentencepiece_reference() {
    let spm = tokenizer();
    let rows = fixture();
    let mut checked = 0usize;
    for row in rows.as_array().expect("fixture is an array") {
        let text = row["text"].as_str().expect("text");
        let want_pieces: Vec<String> = row["pieces"]
            .as_array()
            .expect("pieces")
            .iter()
            .map(|value| value.as_str().expect("piece").to_string())
            .collect();
        let want_ids: Vec<u32> = row["ids"]
            .as_array()
            .expect("ids")
            .iter()
            .map(|value| value.as_u64().expect("id") as u32)
            .collect();

        let got_pieces = spm.encode_pieces(text);
        assert_eq!(got_pieces, want_pieces, "pieces differ for {text:?}");
        assert_eq!(spm.encode_ids(text), want_ids, "ids differ for {text:?}");
        checked += 1;
    }
    assert!(checked >= 60, "fixture looks truncated: {checked} rows");
}

#[test]
fn piece_to_id_round_trips() {
    let spm = tokenizer();
    // CONTROL / UNKNOWN / BYTE pieces live in the reserved map; NORMAL pieces
    // in the trie. Both must be reachable, and an unknown string must land on UNK.
    assert_eq!(spm.piece_to_id(b"[CLS]"), 1);
    assert_eq!(spm.piece_to_id(b"[SEP]"), 2);
    assert_eq!(spm.piece_to_id(b"[UNK]"), 3);
    assert_eq!(spm.piece_to_id(b"<0x41>"), 0x41 + 4);
    assert_eq!(spm.piece_to_id("\u{2581}my".as_bytes()), 312);
    assert_eq!(spm.piece_to_id(b"not-a-piece"), spm.unk_id());
}

#[test]
fn model_shape_matches_the_checkpoint() {
    let spm = tokenizer();
    assert_eq!(spm.len(), 128000, "SP vocab before the 11 added GLiNER tokens");
    assert_eq!(spm.unk_id(), 3);
    // The reference encodes these with no byte fallback, so a plain ASCII word
    // must be a single piece.
    assert_eq!(spm.encode_pieces("refund_request"), ["▁refund", "_", "request"]);
    assert_eq!(spm.encode_pieces("("), ["▁("]);
}
