//! F16×F32 AVX2 (x86_64) matmul kernel.
//!
//! Generated by `avx2_matmul_packed!` in `super::super::simd_avx2`.  F16
//! weight bytes are unpacked with `_mm256_cvtph_ps` (F16C).  See module
//! docs for the shared skeleton.

use crate::avx2_matmul_packed;

#[target_feature(enable = "avx2", enable = "fma", enable = "f16c")]
unsafe fn unpack_f16_8(
    w: *const u8,
    row_byte: usize,
    col: usize,
) -> std::arch::x86_64::__m256 {
    use std::arch::x86_64::*;
    let chunk = _mm_loadu_si128(w.add(row_byte + col * 2) as *const __m128i);
    _mm256_cvtph_ps(chunk)
}

#[target_feature(enable = "avx2", enable = "fma", enable = "f16c")]
unsafe fn unpack_f16_4(
    w: *const u8,
    row_byte: usize,
    col: usize,
) -> std::arch::x86_64::__m128 {
    use std::arch::x86_64::*;
    let half = _mm_loadl_epi64(w.add(row_byte + col * 2) as *const __m128i);
    _mm_cvtph_ps(half)
}

#[target_feature(enable = "avx2", enable = "fma", enable = "f16c")]
unsafe fn scalar_unpack_f16(w: *const u8, row_byte: usize, col: usize) -> f32 {
    let bits = u16::from_le_bytes([
        *w.add(row_byte + col * 2),
        *w.add(row_byte + col * 2 + 1),
    ]);
    crate::ops::f16_to_f32(bits)
}

avx2_matmul_packed!(
    matmul_f16_vs_f32_avx2,
    2,
    unpack_f16_8,
    unpack_f16_4,
    scalar_unpack_f16
);

#[cfg(test)]
mod tests {
    use super::matmul_f16_vs_f32_avx2;
    use crate::ops::kernel::f16::scalar::forward_f16_rows;

    fn assert_avx2_eq_scalar(label: &str, weight: &[u8], input: &[f32], n_in: usize, n_out: usize) {
        let mut avx2_out = vec![0.0f32; n_out];
        let mut scalar_out = vec![0.0f32; n_out];
        unsafe {
            matmul_f16_vs_f32_avx2(weight, input, &mut avx2_out, n_in, 0, n_out);
        }
        forward_f16_rows(weight, input, &mut scalar_out, n_in, n_out, 0, 1);
        for (i, (a, s)) in avx2_out.iter().zip(scalar_out.iter()).enumerate() {
            let denom = s.abs().max(1e-3);
            let rel = (a - s).abs() / denom;
            assert!(
                rel < 1e-3 || (a - s).abs() < 1e-4,
                "{} row {}: avx2={} scalar={} diff={}",
                label,
                i,
                a,
                s,
                (a - s).abs(),
            );
        }
    }

    #[test]
    fn avx2_matches_scalar_small() {
        let n_in = 16;
        let n_out = 4;
        let weight: Vec<u8> = (0..n_in * n_out)
            .flat_map(|i| crate::ops::f32_to_f16((i as f32 * 0.1) - 0.3).to_le_bytes())
            .collect();
        let input: Vec<f32> = (0..n_in).map(|i| (i as f32 - 8.0) * 0.05).collect();
        assert_avx2_eq_scalar("small 4x16", &weight, &input, n_in, n_out);
    }

    #[test]
    fn avx2_matches_scalar_large() {
        let n_in = 256;
        let n_out = 16;
        let weight: Vec<u8> = (0..n_in * n_out)
            .flat_map(|i| {
                crate::ops::f32_to_f16((((i * 13 + 7) % 47) as f32 - 23.0) * 0.01).to_le_bytes()
            })
            .collect();
        let input: Vec<f32> = (0..n_in).map(|i| ((i % 23) as f32 - 11.0) * 0.02).collect();
        assert_avx2_eq_scalar("large 16x256", &weight, &input, n_in, n_out);
    }

    #[test]
    fn avx2_matches_scalar_tail() {
        let n_in = 40;
        let n_out = 3;
        let weight: Vec<u8> = (0..n_in * n_out)
            .flat_map(|i| crate::ops::f32_to_f16((i as f32 * 0.013).sin()).to_le_bytes())
            .collect();
        let input: Vec<f32> = (0..n_in).map(|i| (i as f32 - 20.0) * 0.03).collect();
        assert_avx2_eq_scalar("tail 3x40", &weight, &input, n_in, n_out);
    }
}
