//! Macros that emit AVX2+FMA packed-weight matmul kernels.
//!
//! Used by the BF16 / F16 / F32 kernel trees so the FMA skeleton (32 lanes
//! per outer iteration, 4 accumulators, hsum, 4-lane / scalar tail) lives
//! in one place.  Each caller plugs in its own unpack intrinsics:
//!
//! * BF16: `_mm256_slli_epi32(_mm256_cvtepu16_epi32(...), 16)` (u16→f32 via shift)
//! * F16 : `_mm256_cvtph_ps(...)` (F16C)
//! * F32 : `_mm256_loadu_ps(...)` (no-op)
//!
//! TODO-005: the same macro will eventually subsume
//! `bf16/avx2.rs`, `f16/avx2.rs`, and `f32/avx2.rs`.  Until then the three
//! callers ship a thin macro instantiation per dtype.

#![cfg(target_arch = "x86_64")]

use std::arch::x86_64::__m256;

#[inline(always)]
pub unsafe fn hsum256(v: __m256) -> f32 {
    use std::arch::x86_64::*;
    let hi = _mm256_extractf128_ps(v, 1);
    let lo = _mm256_castps256_ps128(v);
    let s = _mm_add_ps(hi, lo);
    let sh = _mm_movehdup_ps(s);
    let sums = _mm_add_ps(s, sh);
    let shuf = _mm_movehl_ps(sums, sums);
    let final_sum = _mm_add_ss(sums, shuf);
    _mm_cvtss_f32(final_sum)
}

/// Emit an AVX2+FMA packed matmul kernel.
///
/// The caller supplies four unpack helpers as standalone `unsafe` functions
/// (not macros).  Each helper takes `weights: *const u8, row_byte: usize,
/// col: usize` and returns a `__m256` (or `f32` for the scalar tail).
///
/// `$unpack_8(w, r, c) -> __m256`     — load 8 weight lanes starting at
///   `(r, c)` and return them as 8 f32 lanes in a `__m256`.
/// `$unpack_4(w, r, c) -> __m128`     — same but 4 lanes (used for tail).
/// `$scalar_unpack(w, r, c) -> f32`   — read a single f32 weight lane.
#[macro_export]
macro_rules! avx2_matmul_packed {
    (
        $fn_name:ident,
        $bytes_per_element:expr,
        $unpack_8:path,
        $unpack_4:path,
        $scalar_unpack:path
    ) => {
        /// AVX2+FMA packed-weight × F32-input matmul.  Generated by
        /// [`avx2_matmul_packed`].
        #[target_feature(enable = "avx2", enable = "fma")]
        pub unsafe fn $fn_name(
            weight: &[u8],
            input: &[f32],
            output: &mut [f32],
            n_in: usize,
            row_start: usize,
            row_end: usize,
        ) {
            use ::std::arch::x86_64::*;
            let w_ptr = weight.as_ptr();
            let i_ptr = input.as_ptr();
            let out_ptr = output.as_mut_ptr();

            let mut out_local = 0usize;
            for row in row_start..row_end {
                let row_byte = row * n_in * $bytes_per_element;
                let mut acc0 = _mm256_setzero_ps();
                let mut acc1 = _mm256_setzero_ps();

                let mut i = 0;
                while i + 16 <= n_in {
                    let w_lo = $unpack_8(w_ptr, row_byte, i);
                    let w_hi = $unpack_8(w_ptr, row_byte, i + 8);
                    let x_lo = _mm256_loadu_ps(i_ptr.add(i));
                    let x_hi = _mm256_loadu_ps(i_ptr.add(i + 8));
                    acc0 = _mm256_fmadd_ps(w_lo, x_lo, acc0);
                    acc1 = _mm256_fmadd_ps(w_hi, x_hi, acc1);
                    i += 16;
                }
                while i + 8 <= n_in {
                    let w_f = $unpack_8(w_ptr, row_byte, i);
                    let x_f = _mm256_loadu_ps(i_ptr.add(i));
                    acc0 = _mm256_fmadd_ps(w_f, x_f, acc0);
                    i += 8;
                }
                while i + 4 <= n_in {
                    let w_lo128 = $unpack_4(w_ptr, row_byte, i);
                    let zero = _mm256_setzero_ps();
                    let w_f = _mm256_insertf128_ps(zero, w_lo128, 0);
                    let x_f = _mm256_loadu_ps(i_ptr.add(i));
                    acc0 = _mm256_fmadd_ps(w_f, x_f, acc0);
                    i += 4;
                }
                while i < n_in {
                    let w_val = $scalar_unpack(w_ptr, row_byte, i);
                    let x_val = *i_ptr.add(i);
                    acc0 = _mm256_fmadd_ps(
                        _mm256_set1_ps(w_val),
                        _mm256_set1_ps(x_val),
                        acc0,
                    );
                    i += 1;
                }

                let total = unsafe {
                    $crate::ops::kernel::simd_avx2::hsum256(acc0)
                        + $crate::ops::kernel::simd_avx2::hsum256(acc1)
                };
                *out_ptr.add(out_local) = total;
                out_local += 1;
            }
        }
    };
}
