//! F32×F32 AVX2 (x86_64) matmul kernel.
//!
//! Generated by `avx2_matmul_packed!` in `super::super::simd_avx2`.  The
//! unpack helpers are identity `_mm256_loadu_ps` / `_mm_loadu_ps` — F32
//! weight bytes are reinterpreted as `&[f32]` so no dequant step is
//! required.  See module docs for the shared skeleton.

use crate::avx2_matmul_packed;

#[target_feature(enable = "avx2", enable = "fma")]
unsafe fn unpack_f32_8(w: *const u8, row_byte: usize, col: usize) -> std::arch::x86_64::__m256 {
    use std::arch::x86_64::*;
    _mm256_loadu_ps(w.add(row_byte + col * 4) as *const f32)
}

#[target_feature(enable = "avx2", enable = "fma")]
unsafe fn unpack_f32_4(w: *const u8, row_byte: usize, col: usize) -> std::arch::x86_64::__m128 {
    use std::arch::x86_64::*;
    _mm_loadu_ps(w.add(row_byte + col * 4) as *const f32)
}

#[target_feature(enable = "avx2", enable = "fma")]
unsafe fn scalar_unpack_f32(w: *const u8, row_byte: usize, col: usize) -> f32 {
    *(w.add(row_byte + col * 4) as *const f32)
}

avx2_matmul_packed!(
    matmul_f32_vs_f32_avx2,
    4,
    unpack_f32_8,
    unpack_f32_4,
    scalar_unpack_f32
);

#[cfg(test)]
mod tests {
    use super::matmul_f32_vs_f32_avx2;
    use crate::ops::kernel::f32::scalar::forward_f32_rows;

    fn assert_avx2_eq_scalar(label: &str, weight: &[f32], input: &[f32], n_in: usize, n_out: usize) {
        let mut avx2_out = vec![0.0f32; n_out];
        let mut scalar_out = vec![0.0f32; n_out];
        let weight_bytes: &[u8] = bytemuck::cast_slice(weight);
        unsafe {
            matmul_f32_vs_f32_avx2(weight_bytes, input, &mut avx2_out, n_in, 0, n_out);
        }
        forward_f32_rows(weight, input, &mut scalar_out, n_in, n_out, 0, 1);
        for (i, (a, s)) in avx2_out.iter().zip(scalar_out.iter()).enumerate() {
            let denom = s.abs().max(1e-3);
            let rel = (a - s).abs() / denom;
            assert!(
                rel < 1e-3 || (a - s).abs() < 1e-4,
                "{} row {}: avx2={} scalar={} diff={}",
                label,
                i,
                a,
                s,
                (a - s).abs(),
            );
        }
    }

    #[test]
    fn avx2_matches_scalar_small() {
        let n_in = 8;
        let n_out = 4;
        let weight: Vec<f32> = (0..n_in * n_out).map(|i| (i as f32 * 0.1) - 0.3).collect();
        let input: Vec<f32> = (0..n_in).map(|i| (i as f32 - 4.0) * 0.05).collect();
        assert_avx2_eq_scalar("small 4x8", &weight, &input, n_in, n_out);
    }

    #[test]
    fn avx2_matches_scalar_large() {
        let n_in = 256;
        let n_out = 16;
        let weight: Vec<f32> = (0..n_in * n_out)
            .map(|i| (((i * 13 + 7) % 47) as f32 - 23.0) * 0.01)
            .collect();
        let input: Vec<f32> = (0..n_in).map(|i| ((i % 23) as f32 - 11.0) * 0.02).collect();
        assert_avx2_eq_scalar("large 16x256", &weight, &input, n_in, n_out);
    }

    #[test]
    fn avx2_matches_scalar_tail() {
        let n_in = 40;
        let n_out = 3;
        let weight: Vec<f32> = (0..n_in * n_out)
            .map(|i| ((i * 17) as f32 * 0.013).sin())
            .collect();
        let input: Vec<f32> = (0..n_in).map(|i| (i as f32 - 20.0) * 0.03).collect();
        assert_avx2_eq_scalar("tail 3x40", &weight, &input, n_in, n_out);
    }
}
