//! BF16×F32 AVX2 (x86_64) matmul kernel.
//!
//! Generated by `avx2_matmul_packed!` in `super::super::simd_avx2`.  BF16
//! weight bytes are unpacked with `_mm256_cvtepu16_epi32` + `_mm256_slli_epi32`
//! (zero-extend and shift into the F32 high half).  See module docs for the
//! shared skeleton.

use crate::avx2_matmul_packed;

#[target_feature(enable = "avx2", enable = "fma")]
unsafe fn unpack_bf16_8(
    w: *const u8,
    row_byte: usize,
    col: usize,
) -> std::arch::x86_64::__m256 {
    use std::arch::x86_64::*;
    let chunk = _mm_loadu_si128(w.add(row_byte + col * 2) as *const __m128i);
    _mm256_castsi256_ps(_mm256_slli_epi32(_mm256_cvtepu16_epi32(chunk), 16))
}

#[target_feature(enable = "avx2", enable = "fma")]
unsafe fn unpack_bf16_4(
    w: *const u8,
    row_byte: usize,
    col: usize,
) -> std::arch::x86_64::__m128 {
    use std::arch::x86_64::*;
    let half = _mm_loadu_si64(w.add(row_byte + col * 2));
    _mm_castsi128_ps(_mm_slli_epi32(_mm_cvtepu16_epi32(half), 16))
}

#[target_feature(enable = "avx2", enable = "fma")]
unsafe fn scalar_unpack_bf16(w: *const u8, row_byte: usize, col: usize) -> f32 {
    let bits = u16::from_le_bytes([
        *w.add(row_byte + col * 2),
        *w.add(row_byte + col * 2 + 1),
    ]);
    crate::ops::bf16_to_f32(bits)
}

avx2_matmul_packed!(
    matmul_bf16_vs_f32_avx2,
    2,
    unpack_bf16_8,
    unpack_bf16_4,
    scalar_unpack_bf16
);

#[cfg(test)]
mod tests {
    use super::matmul_bf16_vs_f32_avx2;
    use crate::ops::kernel::bf16::scalar::forward_f32_rows_scalar;

    fn assert_avx2_eq_scalar(label: &str, weight: &[u8], input: &[f32], n_in: usize, n_out: usize) {
        let mut avx2_out = vec![0.0f32; n_out];
        let mut scalar_out = vec![0.0f32; n_out];
        unsafe {
            matmul_bf16_vs_f32_avx2(weight, input, &mut avx2_out, n_in, 0, n_out);
        }
        forward_f32_rows_scalar(weight, input, &mut scalar_out, n_in, n_out, 0, 1);
        for (i, (a, s)) in avx2_out.iter().zip(scalar_out.iter()).enumerate() {
            assert!(
                (a - s).abs() < 1e-2,
                "{} row {}: avx2={} scalar={} diff={}",
                label,
                i,
                a,
                s,
                (a - s).abs(),
            );
        }
    }

    #[test]
    fn avx2_matches_scalar_small() {
        let mut weight = Vec::new();
        for r in 0..4 {
            for c in 0..8 {
                weight.extend(crate::ops::f32_to_bf16((r * 8 + c) as f32 * 0.1).to_le_bytes());
            }
        }
        let input: Vec<f32> = (0..8).map(|i| (i as f32 - 4.0) * 0.05).collect();
        assert_avx2_eq_scalar("small 4x8", &weight, &input, 8, 4);
    }

    #[test]
    fn avx2_matches_scalar_large() {
        let n_in = 256;
        let n_out = 16;
        let mut weight = Vec::new();
        for r in 0..n_out {
            for c in 0..n_in {
                weight.extend(
                    crate::ops::f32_to_bf16((((r * n_in + c) % 37) as f32 - 18.0) * 0.01)
                        .to_le_bytes(),
                );
            }
        }
        let input: Vec<f32> = (0..n_in).map(|i| ((i % 23) as f32 - 11.0) * 0.02).collect();
        assert_avx2_eq_scalar("large 16x256", &weight, &input, n_in, n_out);
    }

    #[test]
    fn avx2_matches_scalar_tail() {
        let n_in = 40;
        let n_out = 3;
        let mut weight = Vec::new();
        for r in 0..n_out {
            for c in 0..n_in {
                weight.extend(
                    crate::ops::f32_to_bf16(((r * n_in + c) as f32 * 0.01).sin())
                        .to_le_bytes(),
                );
            }
        }
        let input: Vec<f32> = (0..n_in).map(|i| i as f32 * 0.03).collect();
        assert_avx2_eq_scalar("tail 3x40", &weight, &input, n_in, n_out);
    }
}
